version: "3.9"

services:
  db:
    container_name: compare-db
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  db: